name: build-windows

on: [push, pull_request]

env:
  VCPKG_PATH: C:/vcpkg

jobs:
  build-windows:
    strategy:
      matrix:
        arch: [x86, x64]
        include:
        - arch: x86
          platform: Win32
          triplet: x86-windows
        - arch: x64
          platform: x64
          triplet: x64-windows

    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Setup vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git $env:VCPKG_PATH
        & $env:VCPKG_PATH/bootstrap-vcpkg.bat
        
    - name: Install dependencies
      run: |
        & $env:VCPKG_PATH/vcpkg install --triplet=${{ matrix.triplet }} openssl zlib jansson libevent libxml2 c-ares
        
    - name: Configure CMake
      run: |
        cmake -B build `
          -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_PATH/scripts/buildsystems/vcpkg.cmake" `
          -DCMAKE_GENERATOR_PLATFORM=${{ matrix.platform }} `
          -DVCPKG_TARGET_TRIPLET=${{ matrix.triplet }} `
          -DWITH_ASIO=ON `
          -DWITH_APP=ON `
          -DWITH_HPACK_TOOLS=ON `
          -DWITH_EXAMPLES=ON `
          -DWITH_WIN32APP=ON `
          -DBUILD_TESTING=OFF `
          -DCMAKE_BUILD_TYPE=Release
        
    - name: Build project
      run: |
        cmake --build build --config Release
        
    - name: Find built executables
      id: find_exes
      shell: bash
      run: |
        exe_path=$(find build -type f -name "*.exe" | head -1)
        echo "executables_path=$(dirname $exe_path)" >> $GITHUB_OUTPUT
        
    - name: Create ZIP package
      run: |
        $platform = "${{ matrix.platform }}"
        $archiveName = "nghttp2-${{ github.run_id }}-win-$platform.zip"
        # Create the distribution directory
        New-Item -ItemType Directory -Path "dist/nghttp2/bin"
        
        # Copy all executables
        Copy-Item "${{ steps.find_exes.outputs.executables_path }}/*.exe" -Destination "dist/nghttp2/bin"
        
        # Copy DLL dependencies (assuming they're in the same directory as the executables)
        Copy-Item "${{ steps.find_exes.outputs.executables_path }}/*.dll" -Destination "dist/nghttp2/bin"
        
        # Create the ZIP archive
        Compress-Archive -Path "dist/nghttp2" -DestinationPath $archiveName
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-installer-${{ matrix.platform }}
        path: ${{ github.workspace }}\$archiveName
