name: build-windows

on: [push, pull_request]

env:
  LIBBPF_VERSION: v1.5.1
  OPENSSL1_VERSION: 1_1_1w+quic
  OPENSSL3_VERSION: 3.5.0
  BORINGSSL_VERSION: 9295969e1dad2c31d0d99481734c1c68dcbc6403
  AWSLC_VERSION: v1.52.0
  NGHTTP3_VERSION: v1.10.1
  NGTCP2_VERSION: v1.13.0
  WOLFSSL_VERSION: v5.8.0-stable

jobs:
  build-windows:
    strategy:
      matrix:
        arch: [x86, x64]
        include:
        - arch: x86
          platform: Win32
        - arch: x64
          platform: x64

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: microsoft/setup-msbuild@v2
    - name: Configure cmake
      run: cmake -B build -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_GENERATOR_PLATFORM=${{ matrix.platform }} -DVCPKG_TARGET_TRIPLET=${{ matrix.arch}}-windows -DBUILD_STATIC_LIBS=ON -DBUILD_TESTING=ON
    - name: Build nghttp2
      run: |
        cmake --build build
        cmake --build build --target install
    - name: Create install package
      run: |
        $platform = "${{ matrix.platform }}"
        $archiveName = "nghttp2-${{ github.run_id }}-win-$platform.zip"
        Compress-Archive -Path build/* -DestinationPath $archiveName
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-installer-${{ matrix.platform }}
        path: ${{ github.workspace }}\*.zip
